### ISSUE TITLE
[sonoma|OC|v1.8.1|TM1701] Random screen flicker and static even with DVMT at 64mb, config.plist patch applied and EDID injected

### ISSUE THREAD

**Issue by bamdadkhan** [daliansky/XiaoMi-Pro-Hackintosh#754]
**Pre-requirement**
- For macOS version < Big Sur, try to rebuild the kextcache (e.g. run `sudo kextcache -i /` in `Terminal.app`) and restart whenever you encounter a problem. It always works like a charm!
- If you are using OpenCore, also try to reset NVRAM. Press `Space` key when you are in OpenCore boot page and choose `Reset NVRAM`.

**State the model**
- XiaoMi-Pro MX150, TM1701
 
**State the version of the EFI**
- v1.8.1

**Describe the bug**
- See title. I read through all the documentation and even searched all over the net on how to do an EDID injection - maybe i did it wrong.. it randomly flickers ever few seconds sometimes on boot or after a DPMI off event, only repeatedly changing resolutions and/or refresh rate to 48Hz and back to 60Hz fixes it.

No idea whether it's my fault, so a few pointers in the right direction are appreciated too.

**System log**
- N/A

**Screenshots**
- Hard to capture, but it looks like when a HDMI cable is loose. Similar to TV static.

**Attach your entire EFI folder**
- Please attach your entire EFI folder to help solve your problem.
- Erasing serial numbers in config.plist is required!
[EFI.zip](https://github.com/daliansky/XiaoMi-Pro-Hackintosh/files/13867026/EFI.zip)

**Attach system.log**
- N/A

**Comment by stevezhengshiqi** [comment]
What resolution you are using? Also, did you enable HiDPI?

**Comment by bamdadkhan** [comment]
i'm using 1440x810 and yes, HiDPI is enabled.

**Comment by stevezhengshiqi** [comment]
> i'm using 1440x810 and yes, HiDPI is enabled.

1440x810 is too much for Monterey+, it's better to use 1424x802 as mentioned in https://github.com/daliansky/XiaoMi-Pro-Hackintosh?tab=readme-ov-file#improvements

**Comment by stevezhengshiqi** [comment]
1424x802 is a magic resolution that we conducted mulitple trials. It is a little bit less than 1440x810, and we intentionally avoid perfect 16:9 as it would otherwise flickers.

**Comment by bamdadkhan** [comment]
i'm not getting that one:
<img width="305" alt="Screenshot 2024-05-23 at 1 32 38 AM" src="https://github.com/daliansky/XiaoMi-Pro-Hackintosh/assets/22131327/7b4cba37-c772-4566-bf7e-ceffb3c8ee0e">
am i selecting the wrong options in the HiDPI script?

**Comment by Menchen** [comment]
Rerun the script and follow instruction from https://github.com/xzhih/one-key-hidpi and change the resolution in **system settings**. I think that app overwrites EDID information, thus making the hidpi script useless.

**Comment by bamdadkhan** [comment]
done. first when i switched to it there was some flicker but now it seems fine. i'll test for a day or two and report back. thanks.

**Comment by bamdadkhan** [comment]
well it didn't really work. the flicker is kind of reduced and comes up less often but it's still there, especially after sleep or DPMS off.

**Comment by stevezhengshiqi** [comment]
I would recommend to comment out AAPL00,override-no-connect to undo the EDID injection and then give it a try.
If flicker still happens, consider disabling HiDPI. High version macOS uses Metal V2+ that does not cooperate with our Intel GPU well.
